name: B2CleanLog
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run Id to delete log"
        required: true
jobs:
  B2CleanLog:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all workflow logs
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          RUN_ID: ${{ github.event.inputs.run_id }}
        run: |
          curl -s -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $PAT_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/logs" | jq .
        shell: bash
