name: Delete logs

on:
  repository_dispatch:
    types:
      - delete_logs

jobs:
  delete_logs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all workflow logs
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          RUN_ID: ${{ github.event.client_payload.run_id }}
        run: |
          curl -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $PAT_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/logs"
        shell: bash
