name: Delete logs

on:
  workflow_dispatch:

jobs:
  delete_logs:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for workflow to complete
        run: |
          echo "Waiting for the main job to complete..."
          sleep 60
      - name: Delete all workflow logs
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          run_id=$(curl -s -H "Authorization: token $PAT_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=main&per_page=1" | jq -r '.workflow_runs[0].id')
          repo=${{ github.repository }}
          curl -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $PAT_TOKEN" \
            "https://api.github.com/repos/$repo/actions/runs/$run_id/logs"
        shell: bash
